name: Avanguard Build & Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "avanguard/**"
      - ".github/workflows/build_and_push.yaml"

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_push:
    runs-on: self-hosted
    steps:
    - name: Checkout without submodules
      uses: actions/checkout@v3
      with:
        submodules: false
    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/defguard/avanguard
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=latest,enable=${{ github.event_name != 'pull_request' }}
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha,format=long
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub container registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build container
      uses: docker/build-push-action@v3
      with:
        context: avanguard
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
